name: DiscordSRVJa
version: '${project.version}'
main: io.github.spa77k.discordsrvja.DiscordSRVJaPlugin
api-version: '1.20'
description: Translates death messages and advancement titles sent by DiscordSRV into the server's chosen language.
website: https://github.com/spa77k/mc-discordsrv-ja
depend: [DiscordSRV]
